// <auto-generated />
namespace Investment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update03292018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update03292018));
        
        string IMigrationMetadata.Id
        {
            get { return "201803291454113_Update03.29.2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
